title: Toothpaste Manual
description: Instruction manual for applying toothpaste to a toothbrush
theme: just-the-docs

url: https://ddyszkiewicz.github.io/justTHEdocs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
